DROP TABLE Actividad CASCADE CONSTRAINTS 
;

DROP TABLE Asistencia CASCADE CONSTRAINTS 
;

DROP TABLE Beneficio CASCADE CONSTRAINTS 
;

DROP TABLE Beneficio_Departamento_Empleado CASCADE CONSTRAINTS 
;

DROP TABLE Caracteristica CASCADE CONSTRAINTS 
;

DROP TABLE Caracteristica_Especifica CASCADE CONSTRAINTS 
;

DROP TABLE Cargo CASCADE CONSTRAINTS 
;

DROP TABLE Cerveza CASCADE CONSTRAINTS 
;

DROP TABLE Cheque CASCADE CONSTRAINTS 
;

DROP TABLE Cliente CASCADE CONSTRAINTS 
;

DROP TABLE Cliente_Juridico CASCADE CONSTRAINTS 
;

DROP TABLE Cliente_Natural CASCADE CONSTRAINTS 
;

DROP TABLE Compra CASCADE CONSTRAINTS 
;

DROP TABLE Compra_Estatus CASCADE CONSTRAINTS 
;

DROP TABLE Correo CASCADE CONSTRAINTS 
;

DROP TABLE Cuota_Afiliacion CASCADE CONSTRAINTS 
;

DROP TABLE Departamento CASCADE CONSTRAINTS 
;

DROP TABLE Departamento_Empleado CASCADE CONSTRAINTS 
;

DROP TABLE Descuento CASCADE CONSTRAINTS 
;

DROP TABLE Detalle_Compra CASCADE CONSTRAINTS 
;

DROP TABLE Detalle_Orden_Reposicion CASCADE CONSTRAINTS 
;

DROP TABLE Detalle_Orden_Reposicion_Anaquel CASCADE CONSTRAINTS 
;

DROP TABLE Detalle_Venta_Evento CASCADE CONSTRAINTS 
;

DROP TABLE Efectivo CASCADE CONSTRAINTS 
;

DROP TABLE Empleado CASCADE CONSTRAINTS 
;

DROP TABLE Estatus CASCADE CONSTRAINTS 
;

DROP TABLE Estatus_Orden_Reposicion_Anaquel CASCADE CONSTRAINTS 
;

DROP TABLE Evento CASCADE CONSTRAINTS 
;

DROP TABLE Evento_Proveedor CASCADE CONSTRAINTS 
;

DROP TABLE Evento_Proveedorv1 CASCADE CONSTRAINTS 
;

DROP TABLE Fermentacion CASCADE CONSTRAINTS 
;

DROP TABLE Horario CASCADE CONSTRAINTS 
;

DROP TABLE Horario_Empleado CASCADE CONSTRAINTS 
;

DROP TABLE Horario_Evento CASCADE CONSTRAINTS 
;

DROP TABLE Ingrediente CASCADE CONSTRAINTS 
;

DROP TABLE Instruccion CASCADE CONSTRAINTS 
;

DROP TABLE Inventario CASCADE CONSTRAINTS 
;

DROP TABLE Inventario_Evento_Proveedor CASCADE CONSTRAINTS 
;

DROP TABLE Invitado CASCADE CONSTRAINTS 
;

DROP TABLE Invitado_Evento CASCADE CONSTRAINTS 
;

DROP TABLE Lugar CASCADE CONSTRAINTS 
;

DROP TABLE Membresia CASCADE CONSTRAINTS 
;

DROP TABLE Metodo_Pago CASCADE CONSTRAINTS 
;

DROP TABLE Orden_Reposicion CASCADE CONSTRAINTS 
;

DROP TABLE Orden_Reposicion_Anaquel CASCADE CONSTRAINTS 
;

DROP TABLE Orden_Reposicion_Estatus CASCADE CONSTRAINTS 
;

DROP TABLE Pago_Compra CASCADE CONSTRAINTS 
;

DROP TABLE Pago_Cuota_Afiliacion CASCADE CONSTRAINTS 
;

DROP TABLE Pago_Evento CASCADE CONSTRAINTS 
;

DROP TABLE Pago_Orden_Reposicion CASCADE CONSTRAINTS 
;

DROP TABLE Permiso CASCADE CONSTRAINTS 
;

DROP TABLE Persona_Contacto CASCADE CONSTRAINTS 
;

DROP TABLE Presentacion CASCADE CONSTRAINTS 
;

DROP TABLE Presentacion_Tipo_Cerveza CASCADE CONSTRAINTS 
;

DROP TABLE Privilegio CASCADE CONSTRAINTS 
;

DROP TABLE Promocion CASCADE CONSTRAINTS 
;

DROP TABLE Proveedor CASCADE CONSTRAINTS 
;

DROP TABLE Punto CASCADE CONSTRAINTS 
;

DROP TABLE Punto_Cliente CASCADE CONSTRAINTS 
;

DROP TABLE Receta CASCADE CONSTRAINTS 
;

DROP TABLE Receta_Ingrediente CASCADE CONSTRAINTS 
;

DROP TABLE Rol CASCADE CONSTRAINTS 
;

DROP TABLE Tarjeta_Credito CASCADE CONSTRAINTS 
;

DROP TABLE Tarjeta_Debito CASCADE CONSTRAINTS 
;

DROP TABLE Tasa CASCADE CONSTRAINTS 
;

DROP TABLE Telefono CASCADE CONSTRAINTS 
;

DROP TABLE Tienda_Fisica CASCADE CONSTRAINTS 
;

DROP TABLE Tienda_Web CASCADE CONSTRAINTS 
;

DROP TABLE Tipo_Actividad CASCADE CONSTRAINTS 
;

DROP TABLE Tipo_Cerveza CASCADE CONSTRAINTS 
;

DROP TABLE Tipo_Invitado CASCADE CONSTRAINTS 
;

DROP TABLE TipoEvento CASCADE CONSTRAINTS 
;

DROP TABLE Ubicacion_Tienda CASCADE CONSTRAINTS 
;

DROP TABLE Usuario CASCADE CONSTRAINTS 
;

DROP TABLE Vacacion CASCADE CONSTRAINTS 
;

DROP TABLE Venta_Evento CASCADE CONSTRAINTS 
;

